version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5433:5432" # Forwarding port 5432 (container) na 5433 (host)
    environment:
      POSTGRES_DB: pricetag
      POSTGRES_USER: administrator
      POSTGRES_PASSWORD: StrongPass2024!
    volumes:
      - pg_data:/var/lib/postgresql/data # Keep data after container restart
    networks:
      - pricetag-network

volumes:
  pg_data:

networks:
  pricetag-network:
    driver: bridge
